# Generated by Django 5.2.1 on 2025-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
